routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

Route::resources([
    'users' => 'UserController',
]);

Route::resources([
    'profiles' => 'ProfileController',
]);

Route::get('create_profile/{user_id}', [
    'as' => 'create_profile',
    'uses' => 'ProfileController@create'
]);

Route::post('store_profile/{user_id}', [
    'as' => 'store_profile',
    'uses' => 'ProfileController@store'
]);

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Notifications\Notifiable;
use Jenssegers\Mongodb\Eloquent\Model as Eloquent;
use Jenssegers\Mongodb\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    //Name of the collection
    protected $collection = 'users';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'role'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function profile()
    {
        return $this->hasOne(Profile::class);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth')->only(['index', 'create', 'store', 'edit', 'update', 'destroy']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all()->except(Auth::id());
        return view('user.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('user.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
            'password' => ['required', 'string', 'min:8', 'confirmed'],
        ]);

        $userlist = User::all();
        $userCount = $userlist->count();

        $newuser = new User();
        $newuser->name = $request->get('name');
        $newuser->email = $request->get('email');
        $newuser->password = Hash::make($request->get('password'));
        if ($userCount > 0) {
            $newuser->role = "User";
        } else {
            $newuser->role = "Admin";
        }
        $newuser->save();
        return redirect('users')->with('success', 'User has been  successfully added');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $users = User::find($id);
        return view('user.edit', compact('users', 'id'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user = User::find($id);
        $user->name = $request->get('name');
        $user->email = $request->get('email');
        $user->role = $request->get('role');
        if ($request->has('password')) {
            $user->password = Hash::make($request->get('password'));
        }
        $user->save();
        return redirect('users')->with('success', 'User has been successfully update');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::find($id);
        $user->delete();
        return redirect('users')->with('success', 'User has been  deleted');
    }
}

resources/views/user/create.blade.php
@extends('includes.master')
@section('content')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">User</h1>
                </div>
                <!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{route('home')}}">Home</a></li>
                        <li class="breadcrumb-item"><a href="{{route('users.index')}}">User</a></li>
                        <li class="breadcrumb-item active">Create</li>
                    </ol>
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <!-- Main content -->
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <!-- left column -->
                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Create New User</h3>
                        </div>
                        <!-- /.card-header -->
                        <form method="POST" action="{{ route('users.store') }}">
                            @csrf
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="name">Full Name:</label>
                                    <input id="name" type="text"
                                        class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name"
                                        value="{{ old('name') }}" placeholder="Enter Your Full Name" required autofocus>
                                    @if ($errors->has('name'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span> @endif
                                </div>
                                <div class="form-group">
                                    <label for="email">Email:</label>
                                    <input id="email" type="email"
                                        class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="email"
                                        value="{{ old('email') }}" placeholder="Your E Mail Address">
                                </div>
                                <div class="input-group-append">
                                    @if ($errors->has('email'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('email') }}
                                        </strong>
                                    </span>
                                    @endif
                                </div>
                                <div class="form-group">
                                    <label for="password">Password:</label>
                                    <input id="password" type="password"
                                        class="form-control{{ $errors->has('password') ? ' is-invalid' : '' }}"
                                        name="password" placeholder="Password" required>
                                </div>
                                <div class="form-group">
                                    <label for="password-confirm">Confirm Password:</label>
                                    <input id="password-confirm" type="password" class="form-control"
                                        name="password_confirmation" placeholder="Confirmation Password" required>
                                    <div class="input-group-append">
                                        @if ($errors->has('password'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('password') }}</strong>
                                        </span>
                                        @endif
                                    </div>
                                    <div class="card-footer">
                                        <button type="submit" class="btn btn-primary">Register</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
@endsection

resources/views/user/edit.blade.php
@extends('includes.master')
@section('content')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">User</h1>
                </div>
                <!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{route('home')}}">Home</a></li>
                        <li class="breadcrumb-item"><a href="{{route('users.index')}}">User</a></li>
                        <li class="breadcrumb-item active">Edit</li>
                    </ol>
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <!-- Main content -->
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <!-- left column -->
                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Edit User</h3>
                        </div>
                        <!-- /.card-header -->
                        <form method="post" action="{{route('users.update', $id)}}">
                            @method('PUT')
                            @csrf
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="name">Full Name:</label>
                                    <input type="text" class="form-control" name="name" value="{{$users->name}}">
                                </div>
                                <div class="form-group">
                                    <label for="Model">Email:</label>
                                    <input type="text" class="form-control" name="email" value="{{$users->email}}">
                                </div>
                                @if(Auth::user()->role == "Admin")
                                <div class="form-group">
                                    <label for="role">Role:</label>
                                    <select id="role" name="role">
                                        <option value="User">User</option>
                                        @if($users->role == "Admin")
                                        <option selected value="Admin">Admin</option>
                                        @else
                                        <option value="Admin">Admin</option>
                                        @endif
                                    </select>
                                </div>
                                @else
                                <div class="form-group">
                                    <label for="role">Role:</label>
                                    <select id="role" name="role" disabled>
                                        <option value="User">User</option>
                                        @if($users->role == "Admin")
                                        <option selected value="Admin">Admin</option>
                                        @else
                                        <option value="Admin">Admin</option>
                                        @endif
                                    </select>
                                </div>
                                @endif
                                {{-- <div class="form-group">
                                    <label for="password">Password:</label>
                                    <input id="password" type="password"
                                        class="form-control{{ $errors->has('password') ? ' is-invalid' : '' }}"
                                name="password" placeholder="Password" required>
                            </div> --}}
                            <div class="card-footer">
                                <button type="submit" class="btn btn-success">Update</button>
                            </div>
                    </div>
                    </form>
                </div>
            </div>
        </div>
</div>
</section>
</div>
@endsection

resources/views/user/index.blade.php
@extends('includes.master')
@section('content')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">User</h1>
                </div>
                <!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">User</li>
                    </ol>
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <!-- Main content -->
    <section class="content">
        <div class="col-md-12 mb-3">
            @if(Auth::user()->role == "Admin")
            <a href="{{route('users.create')}}" class="btn btn-primary">Create</a>
            @endif
        </div>
        <div class="container-fluid">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">User Table</h3>
                </div>
                <br />
                @if (\Session::has('success'))
                <div class="alert alert-success">
                    <p>{{ \Session::get('success') }}</p>
                </div><br />
                @endif
                <!-- /.card-header -->
                <div class="card-body">
                    <table id="tbl-user" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th width="10%" style="text-align: center;">Name</th>
                                <th width="15%" style="text-align: center;">Email</th>
                                <th width="15%" style="text-align: center;">Role</th>
                                <th width="20%" style="text-align: center;">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse($users as $index=>$user)
                            <tr>
                                <td>{{$user->name}}</td>
                                <td>{{$user->email}}</td>
                                <td>{{$user->role}}</td>
                                <td class="center">
                                    @if(Auth::user()->role == "Admin")
                                    <a href="{{route('users.edit', $user->id)}}" class="btn btn-info btn-sm">
                                        Edit
                                    </a>
                                    @endif
                                    <a href="{{route('profiles.show', $user->id)}}" class="btn btn-success btn-sm">
                                        Show Profile
                                    </a>
                                    @if(Auth::user()->role == "Admin")
                                    <form class="d-inline" action="{{route('users.destroy', $user->id)}}" method="POST"
                                        onsubmit="return confirm('Move user {{$user->name}} to trash?')">
                                        @csrf
                                        <input type="hidden" value="DELETE" name="_method">
                                        <input type="submit" class="btn btn-danger btn-sm" value="Delete">
                                    </form>
                                    @endif
                                </td>
                            </tr>
                            @empty
                            <tr>
                                <td colspan="3" class="text-center white">No User Except You</td>
                            </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
</div>
<!-- /.container-fluid -->
</section>
<!-- /.content -->
</div>
<!-- /.content-wrapper -->
@endsection
@push('dataTable-script')
<script>
    $.widget.bridge('uibutton', $.ui.button)
</script>
<script>
    $(function () {
            $("#tbl-user").DataTable();
        });
</script>
@endpush